# Generated by Django 3.2.13 on 2022-07-16 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incomingmessagesbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='telegramstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ChatWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(max_length=32)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('tg_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_webhooks', to='incomingmessagesbot.telegramchat')),
                ('tg_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_webhooks', to='incomingmessagesbot.telegramuser')),
            ],
        ),
    ]
