name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Execute deploy command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSH_KEY }}
        script: |
          cd open-telegram-bots/.. || git clone https://github.com/Ali-Toosi/open-telegram-bots.git
          cd open-telegram-bots/ || exit
          git pull
          rm .env.prod.* > /dev/null
          rm .env.dev.* > /dev/null
          echo ${{ secrets.ENV_PROD }} > .env.prod
          echo ${{ secrets.ENV_PROD_DB }} > .env.prod.db
          echo ${{ secrets.ENV_PROD_ACME_COMPANION }} > .env.prod.acme-companion
